package com.whounlockmyphone.captrphotoswhotryunlock23.wtupcp_utils;

import android.media.RingtoneManager;
import com.whounlockmyphone.captrphotoswhotryunlock23.wtupcp_utils.config.WTUPCP_CameraResolution;
import com.whounlockmyphone.captrphotoswhotryunlock23.wtupcp_utils.config.WTUPCP_CameraRotation;
import java.text.SimpleDateFormat;

public class WTUPCP_Constants {
    public static final String ANIM_FIRST_ROW_EXTRA = "animFirst";
    public static final String APP_SESSION_IS_RECORDING = "app_session_is_recording";
    public static final String BROADCAST_UPDATE_UI = "update_ui_broadcast";
    public static final String CURRENT_SESSION_BEGIN = "current_session_begin";
    public static final String CURRENT_SESSION_PHOTO = "current_session_photo";
    public static final String DEVICE_UNLOCKED_EXTRA = "deviceUnlock";
    public static String EXTRA_ALARM_OBJECT = "ALARM INTENT";
    public static String FOLDER_URI = "FOLDER_URI";
    public static String GIVEN_SCOPE = "GIVEN_SCOPE";
    public static final String LAST_SCREEN_EVENT_TYPE = "lastScrnEvnType";
    public static final String LAST_SCREEN_ON_TIME = "lastScreenOnTime";
    public static final String MAIN_URI = "MAIN URI";
    public static final String OFF_SERVICE_EXTRA = "off_service";
    public static int PC_EMAIL = 3;
    public static Integer[] cameraValues = {1, 0};
    public static Integer[] rotValues = {0, 90, Integer.valueOf(WTUPCP_CameraRotation.ROTATION_180), Integer.valueOf(WTUPCP_CameraRotation.ROTATION_270)};
    public static Integer[] resValues = {Integer.valueOf(WTUPCP_CameraResolution.LOW_RESOLUTION), Integer.valueOf(WTUPCP_CameraResolution.MEDIUM_RESOLUTION), Integer.valueOf(WTUPCP_CameraResolution.HIGH_RESOLUTION)};
    public static Integer[] delayValues = {1000, Integer.valueOf(2000), 3000};
    public static final int PHOTO_CAMERA_DEFAULT = cameraValues[0].intValue();
    public static final String PHOTO_CAMERA_PREF = "photoCamera";
    public static final int PHOTO_DELAY_DEFAULT = delayValues[0].intValue();
    public static final int PHOTO_RES_DEFAULT = resValues[1].intValue();
    public static final String PHOTO_RES_PREF = "photoRsltn";
    public static final int PHOTO_ROTATION_DEFAULT = rotValues[3].intValue();
    public static final String PHOTO_ROTATION_PREF = "photoRot";
    public static String PREFERENCE_NAME = "Who Tried to unlock my Phone? Capture Photos";
    public static final String PRE_LAST_SCREEN_EVENT_TYPE = "preLastScreenEvent";
    public static int RC_ALARM_TONE = 5;
    public static int RC_EMAIL_PIC = 4;
    public static final String REPORT_ENTITY = "REPORT ENTITY";
    public static int REQUEST_CAMERA_PERMISSION = 1;
    public static int REQUEST_USAGE_APP_PERMISSION = 2;
    public static final String SAVE_REPORT_EXTRA = "save_report";
    public static String SERVICE_ON = "SERVICE ON OFF";
    public static boolean SERVICE_ON_DEFAULT = false;
    public static String SETTING_ALARM_ON_WRONG_PASSWORD = "SETTING ALARM ON WRONG PASSWORD";
    public static boolean SETTING_ALARM_ON_WRONG_PASSWORD_DEFAULT = true;
    public static String SETTING_ALARM_TONE = "SETTING ALARM TONE";
    public static String SETTING_ALARM_TONE_DEFAULT = RingtoneManager.getDefaultUri(4).toString();
    public static String SETTING_ALERT_ON_EMAIL = "SETTING ALERT ON EMAIL";
    public static boolean SETTING_ALERT_ON_EMAIL_DEFAULT = false;
    public static String SETTING_EMAIL_ADDRESS = "SETTING EMAIL ADDRESS";
    public static String SETTING_EMIAL_ID = "SETTING EMIAL ID";
    public static String SETTING_ENABLE_NOTIFICATION = "SETTING ENABLE NOTIFICATION";
    public static boolean SETTING_ENABLE_NOTIFICATION_DEFAULT = true;
    public static String SETTING_FAIL_UNLOCK_ATTEMPSTS = "SETTING FAIL UNLOCK ATTEMPSTS";
    public static boolean SETTING_FAIL_UNLOCK_ATTEMPSTS_DEFAULT = true;
    public static String SETTING_FLASH_ON_WRONG_PASSWORD = "SETTING FLASH ON WRONG PASSWORD";
    public static boolean SETTING_FLASH_ON_WRONG_PASSWORD_DEFAULT = false;
    public static String SETTING_GOOGLE_DRIVE_SYNC = "SETTING GOOGLE DRIVE SYNC";
    public static String SETTING_NO_OF_ATTEMPS = "SETTING NO OF ATTEMPS";
    public static int SETTING_NO_OF_ATTEMPS_DEFAULT = 1;
    public static String SETTING_SAVE_REPORT_IF_NO_UNLOCK_ATTEMPSTS = "SETTING SAVE REPORT IF NO UNLOCK ATTEMPSTS";
    public static boolean SETTING_SETTING_GOOGLE_DRIVE_SYNC_DEFAULT = false;
    public static boolean SETTING_SETTING_SAVE_REPORT_IF_NO_UNLOCK_ATTEMPSTS_DEFAULT = true;
    public static String SETTING_SHOW_LAUNCHED_APP = "SETTING SHOW LAUNCHED APP";
    public static boolean SETTING_SHOW_LAUNCHED_APP_DEFAULT = false;
    public static String SETTING_SUCCESSFUL_UNLOCK_ATTEMPSTS = "SETTING SUCCESSFUL UNLOCK ATTEMPSTS";
    public static boolean SETTING_SUCCESSFUL_UNLOCK_ATTEMPSTS_DEFAULT = true;
    public static String SETTING_VIBRATE_ON_WRONG_PASSWORD = "SETTING VIBRATE ON WRONG PASSWORD";
    public static boolean SETTING_VIBRATE_ON_WRONG_PASSWORD_DEFAULT = false;
    public static final String SHORT_DATE_FORMAT = "MMM. dd, HH:mm:ss";
    public static final String WRONG_PATTERN_EXTRA = "wrongPattern";

    public static String[] camera_storage_Permission = {"android.permission.CAMERA", "android.permission.WRITE_EXTERNAL_STORAGE"};
    public static String[] camera_storage_Permission_new = {"android.permission.CAMERA"};
    public static SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMM. dd, HH:mm:ss a");
    public static SimpleDateFormat simpleDateFormat1 = new SimpleDateFormat("dd-MM-yyyy");
    public static SimpleDateFormat simpleDateFormat2 = new SimpleDateFormat("d MMM yyyy,h:mm a");
    public static SimpleDateFormat simpleDateFormat3 = new SimpleDateFormat("MMM. dd, hh:mm:ss a");
}
